name: E2E Tests

on:
  push:
    branches:
      - main
    paths:
      - 'e2e-test-front/**'
  pull_request:
    branches:
      - main
    paths:
      - 'e2e-test-front/**'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: e2e-test-front

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Executar testes do Cypress
        run: npx cypress run