name: Load Testing K6

on:
  push:
    branches:
      - main
    paths:
      - 'load-test-k6/**'
  pull_request:
    branches:
      - main
    paths:
      - 'load-test-k6/**'

jobs:
  k6-load-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: load-test-k6

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar K6
        run: |
          curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt update
          sudo apt install -y k6

      - name: Verificar versão do K6
        run: k6 version

      - name: Executar testes de carga
        run: k6 run load-test.js
