name: API Tests

on:
  push:
    branches:
      - main
    paths:
      - 'test-api/**'
  pull_request:
    branches:
      - main
    paths:
      - 'test-api/**'

jobs:
  cypress-api-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test-api  # Define a pasta base

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Executar testes do Cypress
        run: npx cypress run